default_language_version:
  python: python3.11

repos:
  # mypy checks type annotations.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]

  # pre-commit-hooks is a collection of Git hooks for code quality, formatting, and analysis.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-toml
      - id: debug-statements

  # An extremely fast Python linter and code formatter, written in Rust.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.5
    hooks:
    -   id: ruff
        args:
        - --fix
    -   id: ruff-format
