# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whisper_mic_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19whisper_mic_service.proto\x12\x13whisper_mic_service\"\"\n\tAudioData\x12\x15\n\rndarray_bytes\x18\x01 \x01(\x0c\"#\n\rTranscription\x12\x12\n\nprediction\x18\x01 \x01(\t2d\n\nWhisperMic\x12V\n\nStreamData\x12\x1e.whisper_mic_service.AudioData\x1a\".whisper_mic_service.Transcription\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whisper_mic_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIODATA']._serialized_start=50
  _globals['_AUDIODATA']._serialized_end=84
  _globals['_TRANSCRIPTION']._serialized_start=86
  _globals['_TRANSCRIPTION']._serialized_end=121
  _globals['_WHISPERMIC']._serialized_start=123
  _globals['_WHISPERMIC']._serialized_end=223
# @@protoc_insertion_point(module_scope)
