# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# pylint: skip-file
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import faster_whisper_transcription_pb2 as faster__whisper__transcription__pb2


class FasterWhisperTranscriptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamData = channel.stream_stream(
                '/faster_whisper_transcription.FasterWhisperTranscription/StreamData',
                request_serializer=faster__whisper__transcription__pb2.AudioData.SerializeToString,
                response_deserializer=faster__whisper__transcription__pb2.Transcription.FromString,
                )


class FasterWhisperTranscriptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FasterWhisperTranscriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=faster__whisper__transcription__pb2.AudioData.FromString,
                    response_serializer=faster__whisper__transcription__pb2.Transcription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faster_whisper_transcription.FasterWhisperTranscription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FasterWhisperTranscription(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/faster_whisper_transcription.FasterWhisperTranscription/StreamData',
            faster__whisper__transcription__pb2.AudioData.SerializeToString,
            faster__whisper__transcription__pb2.Transcription.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
